{{- if .Values.global.createSecrets }}
{{- with .Values.global.registry -}}
{{- if and .dockerConfigJson (not .existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .dockerConfigJson }}
{{- end }}
{{- end }}
{{- end }}
