apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-obsidian.fullname" . }}
  labels:
    {{- include "mcp-obsidian.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    - port: {{ .Values.service.guiPortHttp }}
      targetPort: gui-http
      protocol: TCP
      name: gui-http
    - port: {{ .Values.service.guiPortHttps }}
      targetPort: gui-https
      protocol: TCP
      name: gui-https
  selector:
    {{- include "mcp-obsidian.selectorLabels" . | nindent 4 }}
