image:
  repository: ghcr.io/jakobkolb/mcp-calendar
  tag: latest

ingress:
  host: calendar.mcp.mydomain.hopto.org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: mcp-calendar-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "MCP Authentication Required"

env:
  CALENDAR_CONFIG: /config/config.yaml

configFile:
  enabled: true
  mountPath: /config/config.yaml
  content: ""   # set in mcp-calendar.secret.yaml
